# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3dcd51ebc6284a8f6300ad5cd6db95ad9470d9018b6beb74b10d289184882b0b3306bb7e8364b4dff0678a49e4bf60ccbae2fdca0d4b3e6acd4379ee020bac94

test:
  secret_key_base: 7f0c5d2c539746b9641e0b179651f5d66dcca834983d9858a9babe943943cc3d1e271ef41048350acb454f7e538b7003b35502a489eaf1582e48c696ebfa9383

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
